### ISSUE TITLE
Lighting not updating in surrounding chunks

### ISSUE THREAD

**Issue by LeQuadratico** [bodhid/Minecraft-In-Unity#1]
![Anmerkung 2020-05-08 203510](https://user-images.githubusercontent.com/45048954/81437454-7c3b2300-916b-11ea-8edf-c105ce486c63.jpg)
When a light block is being placed (e.g. Glowstone) only the chunk of the block is updated.

**Comment by LeQuadratico** [comment]
But nice project, I especially like the lighing functionality!

**Comment by bodhid** [comment]
Thank you for trying out the project!
Light sources other than sunlight are currently only being simulated in their own chunk. 
I will let you know here when it is added :)

**Comment by bodhid** [comment]
Fixed in 95a106c
![minecraftUnityLightSources](https://user-images.githubusercontent.com/11909285/81451384-aea54a00-9184-11ea-9110-53cf4c474175.jpg)
